version: '3.8'

services:
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    restart: unless-stopped
    user: "472:472"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password123
        #- GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
        #- GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    volumes:
      # Volúmenes nombrados para persistencia
      - grafana_storage:/var/lib/grafana
      - grafana_config:/etc/grafana
      - grafana_logs:/var/log/grafana
      
      # Volúmenes bind mount para desarrollo
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/plugins:/var/lib/grafana/plugins
    networks:
      - monitoring

volumes:
  grafana_storage:
    name: grafana-storage
  grafana_config:
    name: grafana-config
  grafana_logs:
    name: grafana-logs

networks:
  monitoring:
    driver: bridge
